# Free signal utilities for token logprob entropy computation (P1.2)

"""Provides a helper to compute the average negative log-probability (entropy) for a claim based on token-level logprobs.
If token logprob data is not available (e.g., when using Gemini without logprob support), the function returns ``0.0``.
"""

from typing import List, Tuple

def compute_claim_logprob_entropy(
    claim_text: str,
    answer_text: str,
    token_logprobs: List[float],
    offsets: List[Tuple[int, int]],
) -> float:
    """Compute the average negative log‑probability (entropy) for a claim.

    Args:
        claim_text: The claim string extracted from the answer.
        answer_text: The full answer text generated by the LLM.
        token_logprobs: List of log‑probability values (natural log) for each token.
        offsets: List of (start_char, end_char) tuples for each token.

    Returns:
        The average negative log‑probability for the claim (float). Returns ``0.0`` if no token data is available or the claim cannot be located.
    """
    if not token_logprobs or not offsets:
        return 0.0
    start_idx = answer_text.find(claim_text)
    if start_idx == -1:
        return 0.0
    end_idx = start_idx + len(claim_text)
    overlapping_logprobs: List[float] = []
    for lp, (tok_start, tok_end) in zip(token_logprobs, offsets):
        if tok_start < end_idx and tok_end > start_idx:
            overlapping_logprobs.append(lp)
    if not overlapping_logprobs:
        return 0.0
    avg_neg_logprob = -sum(overlapping_logprobs) / len(overlapping_logprobs)
    return avg_neg_logprob
